# Generated by Django 2.1.7 on 2019-12-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contestants',
            new_name='Contestant',
        ),
    ]
