# Generated by Django 2.1.7 on 2019-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0003_auto_20191209_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='rank',
            field=models.FloatField(default=False),
        ),
    ]
