# Generated by Django 2.1.7 on 2019-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0004_auto_20191209_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='rank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
