# Generated by Django 2.1.7 on 2019-12-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0005_auto_20191209_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contestants_no',
        ),
    ]
