# Generated by Django 2.1.7 on 2019-12-16 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0006_remove_contest_contestants_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.CharField(max_length=200)),
                ('url', models.CharField(default=0, max_length=100)),
                ('is_vote', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rank.Contest')),
            ],
            options={
                'ordering': ['voter'],
            },
        ),
    ]
