# Generated by Django 2.1.7 on 2020-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0008_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
