# Generated by Django 2.1.7 on 2020-01-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0009_contest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='name',
            new_name='title',
        ),
    ]
