# Generated by Django 2.1.7 on 2020-01-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rank', '0010_auto_20200116_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='o', max_length=20),
        ),
    ]
